### ISSUE TITLE
Name on config is not working.

### ISSUE THREAD

**Issue by sazack** [mac066/mail-template#1]
While setting up the config variable, when a name is set the mailer doesn't send any emails nor does it gives the error response. Connection timeout occurs in a while.
`send: function (options, cb) {
    if (!mailer.config || !mailer.transport) {
      return cb(new Error('Mailer not initialized'));
    }

    var mail = {
      from: options.from || mailer.config.sender,
      subject: mailer.config.subjectPrefix ? mailer.config.subjectPrefix + ' ' + options.subject : options
        .subject,
      html: options.body,
      generateTextFromHTML: options.generateTextFromHTML || true,
      sender: mailer.config.sender || (mailer.config.auth ? mailer.config.auth.user : 'No-name'),
      attachments: options.attachments || [],
      replyTo: options.replyTo || mailer.config.sender
    };

    ['bcc', 'cc', 'to'].forEach(function (key) {
      if (options[key]) {
        mail[key] = options[key];
      }
    });

    mailer.transport.sendMail(mail, cb);
  }
};`

Here this snippet of the code for the mailer doesn't have a name object.

**Comment by mac066** [comment]
first of all you should configure the mailer like this
  var emailConfig={
    email:{
            subjectPrefix :"XX",
            sender:"XX",
            host:'smtp.gmail.com',
            port:465,
            auth:{
                user:'XXX',
                pass:'XXX'
            }
    }
    }

var templateConfig = {
    dir: path.join(__dirname, 'template')
};

var nm = require('./')(emailConfig, templateConfig);

then you can send email like this
 nm.email.send(recipients, options, console.log)
Plz refer to readme file if any confusion
